### ISSUE TITLE
Does not work in Cura 2.5: 'cura.Settings.CuraContainerRegistry' has no attribute 'getInstance'

### ISSUE THREAD

**Issue by probonopd** [probonopd/WirelessPrinting#13]
```
me@host:~$ ./Downloads/Cura-2.5.0-BETA.AppImage 2>&1 | grep ERROR
2017-03-25 16:51:51,723 - ERROR - UM.PluginRegistry.loadPlugin [91]: Plugin VersionUpgrade24to25 did not return any objects to register
2017-03-25 16:51:51,785 - ERROR - UM.Logger.logException [74]: Exception: Error loading plugin WirelessPrinting:
2017-03-25 16:51:51,787 - ERROR - UM.Logger.logException [78]: Traceback (most recent call last):
2017-03-25 16:51:51,788 - ERROR - UM.Logger.logException [78]:   File "/build/2.5/build/inst/lib/python3/dist-packages/UM/PluginRegistry.py", line 89, in loadPlugin
2017-03-25 16:51:51,790 - ERROR - UM.Logger.logException [78]:   File "/home/me/.local/share/cura/plugins/WirelessPrinting/__init__.py", line 21, in register
2017-03-25 16:51:51,791 - ERROR - UM.Logger.logException [78]:     "machine_action": DiscoverWirelessPrintAction.DiscoverWirelessPrintAction()
2017-03-25 16:51:51,793 - ERROR - UM.Logger.logException [78]:   File "/home/me/.local/share/cura/plugins/WirelessPrinting/DiscoverWirelessPrintAction.py", line 29, in __init__
2017-03-25 16:51:51,794 - ERROR - UM.Logger.logException [78]:     cura.Settings.CuraContainerRegistry.getInstance().containerAdded.connect(self._onContainerAdded)
2017-03-25 16:51:51,796 - ERROR - UM.Logger.logException [78]: AttributeError: module 'cura.Settings.CuraContainerRegistry' has no attribute 'getInstance'
```

**Comment by probonopd** [comment]
Closed in https://github.com/probonopd/WirelessPrinting/commit/fb0ad636d1e259020393d8ccaaf9f754ce05d24f
